version: "2"

run:
  allow-parallel-runners: true
  timeout: 5m
  issues-exit-code: 1
  tests: true
  # Performance optimization
  go: '1.25'
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    lll:
      # Reasonable limit that accommodates function signatures and structured logging
      line-length: 160
      tab-width: 4
    dupl:
      # Increase threshold to avoid flagging intentional similar patterns
      threshold: 150
    staticcheck:
      checks: ["all"]
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
