version: "2"
run:
  allow-parallel-runners: true
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []
  skip-dirs:
    - vendor$
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
    dupl:
      threshold: 100
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
    misspell:
      locale: US
    staticcheck:
      go: "1.25"
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - staticcheck
        text: "ST1001" # Allow dot imports in test files
        path: test/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
