# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

set:
  - errexit
  - nounset
  - pipefail

includes:
  build:
    taskfile: ./Taskfile-build.yml
    dir: .
    flatten: true
  e2e:
    taskfile: ./test/e2e/Taskfile.yml
    dir: .
    flatten: true

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
    silent: true

  help:
    desc: Display this help
    aliases:
      - list
    cmds:
      - task --list
    silent: true
