# This rule is not used by the project gitops-reverser itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the configbutler.ai.configbutler.ai.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gitops-reverser
    app.kubernetes.io/managed-by: kustomize
  name: watchrule-editor-role
rules:
- apiGroups:
  - configbutler.ai.configbutler.ai
  resources:
  - watchrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configbutler.ai.configbutler.ai
  resources:
  - watchrules/status
  verbs:
  - get
