# This rule is not used by the project gitops-reverser itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over configbutler.ai.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gitops-reverser
    app.kubernetes.io/managed-by: kustomize
  name: watchrule-admin-role
rules:
- apiGroups:
  - configbutler.ai
  resources:
  - watchrules
  verbs:
  - '*'
- apiGroups:
  - configbutler.ai
  resources:
  - watchrules/status
  verbs:
  - get
