#!/bin/bash
# Prints an audit webhook kubeconfig that trusts the stable audit root CA and
# authenticates kube-apiserver with a dedicated client certificate.

set -euo pipefail

CTX="${CTX:-k3d-gitops-reverser-test-e2e}"
NAMESPACE="${NAMESPACE:-gitops-reverser}"
AUDIT_CLUSTER_ID="${AUDIT_CLUSTER_ID:-kind-e2e}"
AUDIT_WEBHOOK_SERVER_URL="${AUDIT_WEBHOOK_SERVER_URL:-https://127.0.0.1:30444/audit-webhook/${AUDIT_CLUSTER_ID}}"
AUDIT_TLS_SERVER_NAME="${AUDIT_TLS_SERVER_NAME:-gitops-reverser-audit.${NAMESPACE}.svc}"
WAIT_RETRIES="${WAIT_RETRIES:-60}"
WAIT_SECONDS="${WAIT_SECONDS:-2}"

if [[ -n "${AUDIT_ROOT_CA_SECRET:-}" ]]; then
    AUDIT_ROOT_CA_SECRET_CANDIDATES=("${AUDIT_ROOT_CA_SECRET}")
else
    AUDIT_ROOT_CA_SECRET_CANDIDATES=("gitops-reverser-audit-root-ca")
fi

if [[ -n "${AUDIT_CLIENT_SECRET:-}" ]]; then
    AUDIT_CLIENT_SECRET_CANDIDATES=("${AUDIT_CLIENT_SECRET}")
else
    AUDIT_CLIENT_SECRET_CANDIDATES=("audit-client-cert" "gitops-reverser-audit-client-cert")
fi

secret_data() {
    local secret_name="$1"
    local key="$2"
    kubectl --context "${CTX}" get secret "${secret_name}" \
        --namespace "${NAMESPACE}" \
        -o "jsonpath={.data.${key}}" 2>/dev/null || true
}

wait_for_any_secret_key() {
    local key="$1"
    shift
    local secret_names=("$@")
    local value="" secret_name

    for _ in $(seq 1 "${WAIT_RETRIES}"); do
        for secret_name in "${secret_names[@]}"; do
            value="$(secret_data "${secret_name}" "${key}")"
            if [ -n "${value}" ]; then
                printf '%s' "${value}"
                return 0
            fi
        done
        sleep "${WAIT_SECONDS}"
    done

    echo "timed out waiting for one of [${secret_names[*]}] ${key}" >&2
    return 1
}

ROOT_CA_B64="$(wait_for_any_secret_key 'tls\.crt' "${AUDIT_ROOT_CA_SECRET_CANDIDATES[@]}")"
CLIENT_CERT_B64="$(wait_for_any_secret_key 'tls\.crt' "${AUDIT_CLIENT_SECRET_CANDIDATES[@]}")"
CLIENT_KEY_B64="$(wait_for_any_secret_key 'tls\.key' "${AUDIT_CLIENT_SECRET_CANDIDATES[@]}")"

cat <<EOF
# Kubernetes audit webhook configuration for k3d cluster
# Generated by hack/generate-audit-webhook-kubeconfig.sh — do not edit or commit this file.
apiVersion: v1
kind: Config
preferences: {}
clusters:
- name: audit-webhook
  cluster:
    server: ${AUDIT_WEBHOOK_SERVER_URL}
    certificate-authority-data: ${ROOT_CA_B64}
    tls-server-name: ${AUDIT_TLS_SERVER_NAME}
contexts:
- name: webhook
  context:
    cluster: audit-webhook
    user: kube-apiserver
current-context: webhook
users:
- name: kube-apiserver
  user:
    client-certificate-data: ${CLIENT_CERT_B64}
    client-key-data: ${CLIENT_KEY_B64}
EOF
