apiVersion: configbutler.ai.configbutler.ai/v1alpha1
kind: WatchRule
metadata:
  labels:
    app.kubernetes.io/name: gitops-reverser
    app.kubernetes.io/managed-by: kustomize
  name: watchrule-sample
spec:
  gitRepoConfigRef: "gitrepoconfig-sample"
  excludeLabels:
    matchExpressions:
      - key: "configbutler.ai/ignore"
        operator: Exists
  rules:
    - resources: ["deployments", "services", "configmaps", "secrets"]
    - resources: ["ingresses.*"]
