apiVersion: configbutler.ai/v1alpha1
kind: WatchRule
metadata:
  name: watchrule-sample
  namespace: default
spec:
  # Reference to GitRepoConfig
  # If namespace is not specified, defaults to WatchRule's namespace
  gitRepoConfigRef:
    name: gitrepoconfig-sample
    # namespace: default  # Optional - defaults to WatchRule's namespace

  # Optional: Filter resources by labels
  # This example includes resources with app=production and excludes those with ignore label
  objectSelector:
    matchExpressions:
      - key: app
        operator: In
        values: [production]
      - key: gitops-reverser.io/ignore
        operator: DoesNotExist

  # Define which resources to watch (logical OR - matching ANY rule triggers watch)
  rules:
    # Watch config resources on CREATE and UPDATE (ignore DELETE)
    - operations: [CREATE, UPDATE]
      apiGroups: [""] # Core API group
      apiVersions: ["v1"]
      resources: [configmaps, secrets]

    # Watch all operations for app resources
    - operations: [CREATE, UPDATE, DELETE]
      apiGroups: [apps]
      apiVersions: ["v1"]
      resources: [deployments, statefulsets]

    # Watch custom resources (all operations, all versions)
    - apiGroups: [example.com]
      resources: [myapps]
