apiVersion: configbutler.ai/v1alpha1
kind: ClusterWatchRule
metadata:
  name: clusterwatchrule-sample
spec:
  gitRepoConfigRef:
    name: gitrepoconfig-sample
    namespace: gitops-reverser-system
  rules:
    # Rule 1: Watch cluster-scoped resources (Nodes)
    - scope: Cluster
      operations: [CREATE, UPDATE, DELETE]
      apiGroups: [""]
      resources: [nodes]

    # Rule 2: Watch cluster-scoped RBAC resources
    - scope: Cluster
      apiGroups: [rbac.authorization.k8s.io]
      resources: [clusterroles, clusterrolebindings]

    # Rule 3: Watch Deployments in ALL namespaces
    - scope: Namespaced
      apiGroups: [apps]
      resources: [deployments]
      # No namespaceSelector = all namespaces

    # Rule 4: Watch Secrets only in PCI-compliant namespaces
    - scope: Namespaced
      apiGroups: [""]
      resources: [secrets]
      namespaceSelector:
        matchLabels:
          compliance: pci
