# sudo nano /etc/rancher/k3s/audit/policy.yaml
apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "RequestReceived"
rules:
  # Removes noise
  - level: None
    resources:
    # CORE: Drop runtime noise, naked pods, and secrets (let's not write them as long as we don't support encrypting)
    - group: ""
      resources: ["events", "endpoints", "nodes", "pods", "secrets"]

    # AUTH: Drop ephemeral checks (Token/Access Reviews are never stored in Etcd)
    - group: "authentication.k8s.io"
      resources: ["tokenreviews"]
    - group: "authorization.k8s.io"
      resources: ["subjectaccessreviews", "selfsubjectaccessreviews", "localsubjectaccessreviews", "selfsubjectrulesreviews"]

    # SYSTEM: Drop high-frequency heartbeat updates
    - group: "coordination.k8s.io"
      resources: ["leases"]

    # UNIVERSAL: Drop "Status" updates for EVERY resource (Core + CRDs)
    - resources: ["*/status"]

  # Remove HPA actions (also noise, since it's not user intent)
  - level: None
    users: ["system:serviceaccount:kube-system:horizontal-pod-autoscaler"]
    verbs: ["update", "patch"]
    resources:
    - resources: ["*/scale"]

  # Captures intent
  # No resources listed -> Matches everything not dropped in earlier rules
  - level: RequestResponse
    omitManagedFields: true
    verbs:
    - create
    - update
    - patch
    - delete
    - deletecollection
