#!/usr/bin/env bash
# Renders every overlay with `kustomize build` and writes the plain KRM output
# under rendered/<env>/frontend.yaml. The GitOps tool (Argo CD) reads only
# rendered/; it never sees src/. Run from the fixture root.
set -euo pipefail

overlays_dir="src/frontend/overlays"
out_dir="rendered"
commit="$(git rev-parse --short HEAD)"

for overlay in "${overlays_dir}"/*/; do
  env="$(basename "${overlay}")"
  out="${out_dir}/${env}/frontend.yaml"
  mkdir -p "$(dirname "${out}")"
  {
    printf '# Generated by `kustomize build %s`. DO NOT EDIT.\n' "${overlay%/}"
    printf '# Source commit: %s. Regenerate with src/render.sh.\n' "${commit}"
    kustomize build "${overlay}"
  } > "${out}"
  echo "rendered ${out}"
done
