# /etc/rancher/k3s/audit/audit-policy.yaml
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Log everything about these resources
  - level: RequestResponse
    verbs:
    - create
    - update
    - patch
    - delete
    - deletecollection
    resources:
    - group: ""
      resources: ["pods", "configmaps"]
    - group : "v1"
      resources: ["deployments"]
