apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "gitops-reverser.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "gitops-reverser.labels" . | nindent 4 }}
  {{- if .Values.certificates.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "gitops-reverser.fullname" . }}-admission-server-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "gitops-reverser.fullname" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.service.ports.admission }}
      path: /validate-configbutler-ai-v1alpha1-gittarget
    {{- if not .Values.certificates.certManager.enabled }}
    caBundle: {{ .Values.webhook.caBundle | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: vgittarget.kb.io
  rules:
  - apiGroups:
    - configbutler.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gittargets
  sideEffects: None
