{{- if .Values.webhook.enabled }}
{{- if .Values.leaderOnlyService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-reverser.fullname" . }}-leader-only
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitops-reverser.labels" . | nindent 4 }}
    app.kubernetes.io/component: leader-only
spec:
  type: ClusterIP
  ports:
    - name: webhook-server
      port: 443
      targetPort: {{ .Values.webhook.server.port }}
      protocol: TCP
  selector:
    {{- include "gitops-reverser.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
    role: leader
{{- end }}
{{- end }}