{{- if and .Values.webhook.enabled .Values.webhook.mutating.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhookConfiguration
metadata:
  name: {{ include "gitops-reverser.fullname" . }}-mutating-webhook-configuration
  labels:
    {{- include "gitops-reverser.labels" . | nindent 4 }}
  {{- if and .Values.certificates.certManager.enabled (hasKey .Values.certificates "webhook") (hasKey .Values.certificates.webhook "secretName") }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.certificates.webhook.secretName }}
  {{- end }}
webhooks:
- name: mutate.gitops-reverser.configbutler.ai
  clientConfig:
    service:
      name: {{ include "gitops-reverser.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate
    {{- if not .Values.certificates.certManager.enabled }}
    caBundle: {{ .Values.webhook.caBundle | b64enc }}
    {{- end }}
  rules:
  {{- range .Values.webhook.mutating.rules }}
  - operations: {{ .operations | toJson }}
    apiGroups: {{ .apiGroups | toJson }}
    apiVersions: {{ .apiVersions | toJson }}
    resources: {{ .resources | toJson }}
    {{- if .scope }}
    scope: {{ .scope }}
    {{- end }}
  {{- end }}
  failurePolicy: {{ .Values.webhook.mutating.failurePolicy }}
  sideEffects: {{ .Values.webhook.mutating.sideEffects }}
  admissionReviewVersions: {{ .Values.webhook.mutating.admissionReviewVersions | toJson }}
  {{- with .Values.webhook.mutating.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.webhook.mutating.objectSelector }}
  objectSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.webhook.mutating.timeoutSeconds }}
  timeoutSeconds: {{ .Values.webhook.mutating.timeoutSeconds }}
  {{- end }}
  {{- if .Values.webhook.mutating.reinvocationPolicy }}
  reinvocationPolicy: {{ .Values.webhook.mutating.reinvocationPolicy }}
  {{- end }}
{{- end }}