{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gitops-reverser.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitops-reverser.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gitops-reverser.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow webhook traffic
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.webhook.server.port }}
    # Allow metrics traffic
    {{- if ne .Values.controllerManager.metrics.bindAddress "0" }}
    - from: []
      ports:
        - protocol: TCP
          port: 8443
    {{- end }}
    # Allow health probe traffic
    - from: []
      ports:
        - protocol: TCP
          port: {{ regexReplaceAll "^:" .Values.controllerManager.healthProbe.bindAddress "" }}
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow Kubernetes API access
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    # Allow Git operations (HTTPS)
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow Git operations (SSH)
    - to: []
      ports:
        - protocol: TCP
          port: 22
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}