apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-reverser.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitops-reverser.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: webhook-server
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.webhook.server.port }}
      protocol: TCP
  selector:
    {{- include "gitops-reverser.selectorLabels" . | nindent 4 }}