{{- if  .Values.webhook.validating.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "gitops-reverser.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "gitops-reverser.labels" . | nindent 4 }}
  {{- if .Values.certificates.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "gitops-reverser.fullname" . }}-serving-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "gitops-reverser.fullname" . }}-leader-only
      namespace: {{ .Release.Namespace }}
      path: /process-audit-webhook-calls
    {{- if not .Values.certificates.certManager.enabled }}
    caBundle: {{ .Values.webhook.caBundle | b64enc }}
    {{- end }}
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  name: gitops-reverser.configbutler.ai
  rules:
  {{- range .Values.webhook.validating.rules }}
  - operations: {{ .operations | toJson }}
    apiGroups: {{ .apiGroups | toJson }}
    apiVersions: {{ .apiVersions | toJson }}
    resources: {{ .resources | toJson }}
    {{- if .scope }}
    scope: {{ .scope }}
    {{- end }}
  {{- end }}
  sideEffects: {{ .Values.webhook.validating.sideEffects }}
  {{- with .Values.webhook.validating.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.webhook.validating.objectSelector }}
  objectSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.webhook.validating.timeoutSeconds }}
  timeoutSeconds: {{ .Values.webhook.validating.timeoutSeconds }}
  {{- end }}
{{- end }}
