{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-reverser.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitops-reverser.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  {{- with .Values.webhookService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhookService.type }}
  ports:
    - name: webhook-server
      port: {{ .Values.webhookService.port }}
      protocol: TCP
      targetPort: {{ .Values.webhookService.targetPort }}
  selector:
    {{- include "gitops-reverser.selectorLabels" . | nindent 4 }}
{{- end }}