#!/bin/bash
set -euo pipefail

# Port-forward the Argo CD web UI and print the admin credentials.
#
# Mirrors hack/e2e/setup-port-forwards.sh: the forward is detached with setsid so
# it survives this shell, is verified for both liveness and a healthy endpoint,
# and is reused on the fast path when already up.
#
# Argo CD is only installed in the bi-directional e2e corner
# (docs/design/e2e-bi-directional-corner.md), so this is a standalone script
# rather than another service in setup-port-forwards.sh — the default
# prepare-e2e must not try to forward a Service that does not exist.
#
# The admin password is generated by argocd-server on first start and stored in
# the argocd-initial-admin-secret Secret. Nothing is committed to the repo.
#
# Inputs (env):
# - CTX / E2E_KUBECONTEXT (required): kube context
# - ARGOCD_NAMESPACE (optional, default argocd)
# - ARGOCD_PORT (optional, default 18080): local port
# - REMOTE_PORT (optional, default 80): argocd-server Service port. The Service
#   exposes 80 (http) and 443 (https); with server.insecure=true the http port
#   is plain HTTP, which is what makes a browser work through the forward.

KUBE_CONTEXT="${E2E_KUBECONTEXT:-${CTX:-}}"
ARGOCD_NAMESPACE="${ARGOCD_NAMESPACE:-argocd}"
ARGOCD_PORT="${ARGOCD_PORT:-18080}"
REMOTE_PORT="${REMOTE_PORT:-80}"

if [[ -z "${KUBE_CONTEXT}" ]]; then
    KUBE_CONTEXT="$(kubectl config current-context 2>/dev/null || true)"
fi
[[ -n "${KUBE_CONTEXT}" ]] || { echo "❌ kube context is required (set CTX/E2E_KUBECONTEXT)"; exit 1; }

kc() { kubectl --context "${KUBE_CONTEXT}" -n "${ARGOCD_NAMESPACE}" "$@"; }

# /healthz is served unauthenticated by argocd-server.
healthy() { curl -fsS "http://127.0.0.1:${ARGOCD_PORT}/healthz" >/dev/null 2>&1; }

print_credentials() {
    local password
    # Generated by argocd-server's InitializeSettings on first start. Absent if an
    # operator has already rotated the admin password out of band.
    password="$(kc get secret argocd-initial-admin-secret \
        -o jsonpath='{.data.password}' 2>/dev/null | base64 -d 2>/dev/null || true)"

    echo
    echo "  Argo CD UI:  http://localhost:${ARGOCD_PORT}"
    echo "  username:    admin"
    if [[ -n "${password}" ]]; then
        echo "  password:    ${password}"
    else
        echo "  password:    <argocd-initial-admin-secret not found — was it rotated or deleted?>"
    fi
    echo
}

if healthy; then
    echo "✅ Argo CD UI port-forward already healthy on http://127.0.0.1:${ARGOCD_PORT}"
    print_credentials
    exit 0
fi

echo "🧹 Cleaning up any stale Argo CD port-forward on ${ARGOCD_PORT}…"
pkill -f "kubectl.*port-forward.*${ARGOCD_PORT}:${REMOTE_PORT}" 2>/dev/null || true
sleep 1

echo "⏳ Waiting for argocd-server to be ready…"
if ! kc rollout status deployment/argocd-server --timeout=180s >/dev/null 2>&1; then
    echo "❌ argocd-server is not ready in namespace ${ARGOCD_NAMESPACE}"
    echo "   Is Argo CD installed? Run: task test-e2e-bi-directional (or task argocd-ui)"
    kc get pods 2>/dev/null || true
    exit 1
fi

echo "🔌 Starting Argo CD UI port-forward (${ARGOCD_PORT} -> svc/argocd-server:${REMOTE_PORT})…"
pf_log="/tmp/argocd-ui-pf.log"
setsid kubectl --context "${KUBE_CONTEXT}" -n "${ARGOCD_NAMESPACE}" port-forward --address 127.0.0.1 \
    "svc/argocd-server" "${ARGOCD_PORT}:${REMOTE_PORT}" >"${pf_log}" 2>&1 < /dev/null &
pf_pid=$!

for _ in $(seq 1 15); do
    if ! kill -0 "${pf_pid}" 2>/dev/null; then
        echo "❌ Argo CD port-forward process died:"; sed 's/^/   /' "${pf_log}" 2>/dev/null || true
        exit 1
    fi
    if healthy; then
        echo "✅ Argo CD UI port-forward verified"
        print_credentials
        exit 0
    fi
    sleep 1
done

echo "❌ Argo CD UI did not become healthy after 15s:"; sed 's/^/   /' "${pf_log}" 2>/dev/null || true
exit 1
