#!/bin/bash
# Injects the cert-manager-issued CA bundle into the audit webhook config and restarts
# the k3d server node so kube-apiserver picks it up.
#
# Must run after the operator is deployed and cert-manager has issued the audit cert.
# Updates test/e2e/cluster/audit/webhook-config.yaml in place (the k3d volume-mounted path).

set -euo pipefail

CTX="${CTX:-k3d-gitops-reverser-test-e2e}"
CLUSTER_NAME="${CLUSTER_NAME:-gitops-reverser-test-e2e}"
NAMESPACE="${NAMESPACE:-gitops-reverser}"
CERT_SECRET="audit-server-cert"
WEBHOOK_CONFIG="test/e2e/cluster/audit/webhook-config.yaml"
SERVER_CONTAINER="k3d-${CLUSTER_NAME}-server-0"

echo "⏳ Waiting for audit TLS cert to be issued (secret: ${CERT_SECRET} in ns ${NAMESPACE})..."
for i in $(seq 1 60); do
    CA_B64=$(kubectl --context "${CTX}" get secret "${CERT_SECRET}" \
        --namespace "${NAMESPACE}" \
        -o jsonpath='{.data.ca\.crt}' 2>/dev/null || true)
    if [ -n "${CA_B64}" ]; then
        break
    fi
    if [ "${i}" -eq 60 ]; then
        echo "❌ Timed out waiting for ${CERT_SECRET} ca.crt" >&2
        exit 1
    fi
    sleep 2
done

echo "🔐 Writing webhook config with CA bundle..."
cat > "${WEBHOOK_CONFIG}" <<EOF
# Kubernetes audit webhook configuration for k3d cluster
# Generated by hack/e2e/inject-webhook-tls.sh — do not edit or commit this file.
apiVersion: v1
kind: Config
preferences: {}
clusters:
- name: audit-webhook
  cluster:
    server: https://127.0.0.1:30444/audit-webhook/kind-e2e
    certificate-authority-data: ${CA_B64}
contexts:
- name: webhook
  context:
    cluster: audit-webhook
    user: kube-apiserver
current-context: webhook
users:
- name: kube-apiserver
  user: {}
EOF

echo "🔄 Restarting k3d server node '${SERVER_CONTAINER}' to reload webhook config..."
docker restart "${SERVER_CONTAINER}"

echo "⏳ Waiting for cluster API to come back..."
for i in $(seq 1 40); do
    if kubectl --context "${CTX}" --request-timeout=5s get ns >/dev/null 2>&1; then
        echo "✅ Cluster healthy — webhook TLS injection complete"
        exit 0
    fi
    sleep 3
done

echo "❌ Cluster did not recover after node restart" >&2
exit 1
